const Categories = [
    {
        id: 1,
        name: "CALAMARI",
        price: 4,
        category: 'Appetizers',
    },
    {
        id: 2,
        name: "PRETZEL BITES",
        price: 4,
        category: 'Appetizers',
    },
    {
        id: 3,
        name: "ONION RINGS",
        price: 4,
        category: 'Appetizers',
    },
    {
        id: 4,
        name: "MOZZARELLA STICKS",
        price: 4,
        category: 'Appetizers',
    },
    {
        id: 5,
        name: "FRIED PICKLES",
        price: 4,
        category: 'Appetizers',
    },
    {
        id: 6,
        name: "FAMILY NACHOS",
        price: 4,
        category: 'Appetizers',
    },
    {
        id: 7,
        name: "CHICKEN TENDERS",
        price: 4,
        category: 'Appetizers',
    },
    {
        id: 8,
        name: "CAESAR SALAD",
        price: 4,
        category: 'Salads',
    },
    {
        id: 9,
        name: "CHEF SALAD",
        price: 4,
        category: 'Salads',
    },
    {
        id: 10,
        name: "BBQ CHICKEN SALAD",
        price: 4,
        category: 'Salads',
    },
    {
        id: 11,
        name: "COBB SALAD",
        price: 4,
        category: 'Salads',
    },
    {
        id: 12,
        name: "ZACH'S HOUSE SALAD",
        price: 4,
        category: 'Salads',
    },
    {
        id: 13,
        name: "CALI ZEST SALAD",
        price: 4,
        category: 'Salads',
    },
    {
        id: 14,
        name: "SPECIAL PEAR SALAD",
        price: 4,
        category: 'Salads',
    },
    {
        id: 15,
        name: "CLASSIC CHEESEBURGER",
        price: 4,
        category: 'Burgers',
    },
    {
        id: 16,
        name: "BACON BURGER",
        price: 4,
        category: 'Burgers',
    },
    {
        id: 17,
        name: "BREAKFAST BURGER",
        price: 4,
        category: 'Burgers',
    },
    {
        id: 18,
        name: "HAWAIIN BURGER",
        price: 4,
        category: 'Burgers',
    },
    {
        id: 19,
        name: "BBQ BURGER",
        price: 4,
        category: 'Burgers',
    },
    {
        id: 20,
        name: "TURKEY BURGER",
        price: 4,
        category: 'Burgers',
    },
    {
        id: 21,
        name: "COLOSSAL BURGER",
        price: 4,
        category: 'Burgers',
    },
    {
        id: 22,
        name: "IMPOSSIBLE BURGER",
        price: 4,
        category: 'Burgers',
    },
    {
        id: 23,
        name: "TUNA MELT",
        price: 4,
        category: 'Burgers',
    },
    {
        id: 24,
        name: "LIL BURGER",
        price: 4,
        category: 'Kids',
    },
    {
        id: 25,
        name: "LIL MAC & CHEESE",
        price: 4,
        category: 'Kids',
    },
    {
        id: 26,
        name: "KIDS CHICKEN TENDERS",
        price: 4,
        category: 'Kids',
    },
    {
        id: 27,
        name: "LIL NUGS",
        price: 4,
        category: 'Kids',
    },
    {
        id: 28,
        name: "ITALIAN DOUGHNUTS",
        price: 4,
        category: 'Desserts',
    },
    {
        id: 29,
        name: "CINIMON BITES",
        price: 4,
        category: 'Desserts',
    },
    {
        id: 30,
        name: "TIRAMISU",
        price: 4,
        category: 'Desserts',
    },
    {
        id: 31,
        name: "SPECIAL CHEESCAKE",
        price: 4,
        category: 'Desserts',
    },
    {
        id: 32,
        name: "CHOCOLATE BROWNIE CAKE",
        price: 4,
        category: 'Desserts',
    },
    {
        id: 33,
        name: "MILKSHAKES",
        price: 4,
        category: 'Desserts',
    },
    {
        id: 34,
        name: "LEMONADE",
        price: 4,
        category: 'Drinks',
    },
    {
        id: 35,
        name: "SPRITE",
        price: 4,
        category: 'Drinks',
    },
    {
        id: 36,
        name: "COCA COLA",
        price: 4,
        category: 'Drinks',
    },
    {
        id: 37,
        name: "DIET COKE",
        price: 4,
        category: 'Drinks',
    },
    {
        id: 38,
        name: "FANTA",
        price: 4,
        category: 'Drinks',
    },
    {
        id: 39,
        name: "KIDS JUICE",
        price: 4,
        category: 'Drinks',
    },
    {
        id: 40,
        name: "FRENCH FRIES",
        price: 4,
        category: 'Sides',
    },
    {
        id: 41,
        name: "SWEET POTATO FRIES",
        price: 4,
        category: 'Sides',
    },
    {
        id: 42,
        name: "MAC & CHEESE",
        price: 4,
        category: 'Sides',
    },
    {
        id: 43,
        name: "MASH POTATOES",
        price: 4,
        category: 'Sides',
    },
    {
        id: 44,
        name: "CHILI",
        price: 4,
        category: 'Sides',
    },
    {
        id: 45,
        name: "ROASTED VEGGIES",
        price: 4,
        category: 'Sides',
    },
    {
        id: 46,
        name: "ONION RINGS",
        price: 4,
        category: 'Sides',
    },
    {
        id: 47,
        name: "BAKED POTATO",
        price: 4,
        category: 'Sides',
    },
    {
        id: 48,
        name: "FRESH FRUIT",
        price: 4,
        category: 'Sides',
    },
]

export default Categories;