const Categories = [
        {
            id: 1,
            name: "CALAMARI",
            price: 4,
            category: 'Appetizers',
        },
        {
            id: 2,
            name: "PRETZEL BITES",
            price: 4,
            category: 'Appetizers',
        },
        {
            id: 3,
            name: "ONION RINGS",
            price: 4,
            category: 'Appetizers',
        },
        {
            id: 4,
            name: "MOZZARELLA STICKS",
            price: 4,
            category: 'Appetizers',
        },
        {
            id: 5,
            name: "FRIED PICKLES",
            price: 4,
            category: 'Appetizers',
        },
        {
            id: 6,
            name: "FAMILY NACHOS",
            price: 4,
            category: 'Appetizers',
        },
        {
            id: 7,
            name: "CHICKEN TENDERS",
            price: 4,
            category: 'Appetizers',
        },
        {
            id: 8,
            name: "CAESAR SALAD",
            price: 4,
            category: 'Salads',
        },
        {
            id: 8,
            name: "CHEF SALAD",
            price: 4,
            category: 'Salads',
        },
        {
            id: 8,
            name: "BBQ CHICKEN SALAD",
            price: 4,
            category: 'Salads',
        },
        {
            id: 8,
            name: "COBB SALAD",
            price: 4,
            category: 'Salads',
        },
        {
            id: 8,
            name: "ZACH'S HOUSE SALAD",
            price: 4,
            category: 'Salads',
        },
        {
            id: 8,
            name: "CALI ZEST SALAD",
            price: 4,
            category: 'Salads',
        },
        {
            id: 8,
            name: "SPECIAL PEAR SALAD",
            price: 4,
            category: 'Salads',
        },
        {
            id: 8,
            name: "CLASSIC CHEESEBURGER",
            price: 4,
            category: 'Burgers',
        },
        {
            id: 8,
            name: "BACON BURGER",
            price: 4,
            category: 'Burgers',
        },
        {
            id: 8,
            name: "BREAKFAST BURGER",
            price: 4,
            category: 'Burgers',
        },
        {
            id: 8,
            name: "HAWAIIN BURGER",
            price: 4,
            category: 'Burgers',
        },
        {
            id: 8,
            name: "BBQ BURGER",
            price: 4,
            category: 'Burgers',
        },
        {
            id: 8,
            name: "TURKEY BURGER",
            price: 4,
            category: 'Burgers',
        },
        {
            id: 8,
            name: "COLOSSAL BURGER",
            price: 4,
            category: 'Burgers',
        },
        {
            id: 8,
            name: "IMPOSSIBLE BURGER",
            price: 4,
            category: 'Burgers',
        },
        {
            id: 8,
            name: "TUNA MELT",
            price: 4,
            category: 'Burgers',
        },
        {
            id: 8,
            name: "LIL BURGER",
            price: 4,
            category: 'Kids',
        },
        {
            id: 8,
            name: "LIL MAC & CHEESE",
            price: 4,
            category: 'Kids',
        },
        {
            id: 8,
            name: "KIDS CHICKEN TENDERS",
            price: 4,
            category: 'Kids',
        },
        {
            id: 8,
            name: "LIL NUGS",
            price: 4,
            category: 'Kids',
        },
        {
            id: 8,
            name: "ITALIAN DOUGHNUTS",
            price: 4,
            category: 'Desserts',
        },
        {
            id: 8,
            name: "CINIMON BITES",
            price: 4,
            category: 'Desserts',
        },
        {
            id: 8,
            name: "TIRAMISU",
            price: 4,
            category: 'Desserts',
        },
        {
            id: 8,
            name: "SPECIAL CHEESCAKE",
            price: 4,
            category: 'Desserts',
        },
        {
            id: 8,
            name: "CHOCOLATE BROWNIE CAKE",
            price: 4,
            category: 'Desserts',
        },
        {
            id: 8,
            name: "MILKSHAKES",
            price: 4,
            category: 'Desserts',
        },
        {
            id: 8,
            name: "LEMONADE",
            price: 4,
            category: 'Drinks',
        },
        {
            id: 8,
            name: "SPRITE",
            price: 4,
            category: 'Drinks',
        },
        {
            id: 8,
            name: "COCA COLA",
            price: 4,
            category: 'Drinks',
        },
        {
            id: 8,
            name: "DIET COKE",
            price: 4,
            category: 'Drinks',
        },
        {
            id: 8,
            name: "FANTA",
            price: 4,
            category: 'Drinks',
        },
        {
            id: 8,
            name: "KIDS JUICE",
            price: 4,
            category: 'Drinks',
        },
        {
            id: 8,
            name: "FRENCH FRIES",
            price: 4,
            category: 'Sides',
        },
        {
            id: 8,
            name: "SWEET POTATO FRIES",
            price: 4,
            category: 'Sides',
        },
        {
            id: 8,
            name: "MAC & CHEESE",
            price: 4,
            category: 'Sides',
        },
        {
            id: 8,
            name: "MASH POTATOES",
            price: 4,
            category: 'Sides',
        },
        {
            id: 8,
            name: "CHILI",
            price: 4,
            category: 'Sides',
        },
        {
            id: 8,
            name: "ROASTED VEGGIES",
            price: 4,
            category: 'Sides',
        },
        {
            id: 8,
            name: "ONION RINGS",
            price: 4,
            category: 'Sides',
        },
        {
            id: 8,
            name: "BAKED POTATO",
            price: 4,
            category: 'Sides',
        },
        {
            id: 8,
            name: "FRESH FRUIT",
            price: 4,
            category: 'Sides',
        },
    ]


    export default Categories;